### PR TITLE
Fuddu Error

### PR DESCRIPTION
**Pull request by SangeetaMishra**
thank me later

### CODE REVIEW

**Comment by adarshagr8** [comment]
:"(

**Comment by SangeetaMishra** [comment]
- [ ] thank you Sangeeta 

check when done

**Comment by adarshagr8** [comment]
Thanks for fuddu PR

**Comment by SangeetaMishra** [comment]
> fuddu PR

Why did you merge? :P

**Comment by adarshagr8** [comment]
> Why did you merge?

I was been blackmailed

**Comment by SangeetaMishra** [comment]
> > Why did you merge?
> 
> I was been blackmailed

Your snippets have so many errors. Let me correct them, Adarsh.

**Comment by adarshagr8** [comment]
> > > Why did you merge?
> > 
> > 
> > I was been blackmailed
> 
> Your snippets have so many errors. Let me correct them, Adarsh.

Sure, I'll put an easter egg for you now.

**Comment by SangeetaMishra** [comment]
> > > > Why did you merge?
> > > 
> > > 
> > > I was been blackmailed
> > 
> > 
> > Your snippets have so many errors. Let me correct them, Adarsh.
> 
> Sure, I'll put an easter egg for you now.

Only one? :'(

**Comment by adarshagr8** [comment]
> > > > > Why did you merge?
> > > > 
> > > > 
> > > > I was been blackmailed
> > > 
> > > 
> > > Your snippets have so many errors. Let me correct them, Adarsh.
> > 
> > 
> > Sure, I'll put an easter egg for you now.
> 
> Only one? :'(

Good Luck finding one

**Comment by SangeetaMishra** [comment]
> > > > > > Why did you merge?
> > > > > 
> > > > > 
> > > > > I was been blackmailed
> > > > 
> > > > 
> > > > Your snippets have so many errors. Let me correct them, Adarsh.
> > > 
> > > 
> > > Sure, I'll put an easter egg for you now.
> > 
> > 
> > Only one? :'(
> 
> Good Luck finding one

Enough for today. I have already found many bugs.

**Pull request merged**
